// @flow
export const SPLASH: 'ROOT/SPLASH' = 'ROOT/SPLASH';
export const MENU: 'ROOT/MENU' = 'ROOT/MENU';
export const GAME: 'ROOT/GAME' = 'ROOT/GAME';
export const GAME_SELECTION: 'ROOT/GAME_SELECTION' = 'ROOT/GAME_SELECTION';
export const PACK_SELECTION: 'ROOT/PACK_SELECTION' = 'ROOT/PACK_SELECTION';
